openapi: 3.1.0
info:
    version: 1.0.0
    title: Foodie app
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    description: This is a documentation of foodie's app
tags:
    - name: Users
      description: Auth operations, user info and list operation with followers.
servers:
    - url: http://localhost:3000/api
paths:
    /users/register:
        post:
            $ref: ../swagger/paths/users/register.yaml
    /users/login:
        post:
            $ref: ../swagger/paths/users/login.yaml
    /users/logout:
        post:
            $ref: ../swagger/paths/users/logout.yaml
    /users/current:
        get:
            $ref: ../swagger/paths/users/current.yaml
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
