openapi: 3.1.0
info:
    version: 1.0.0
    title: Foodie's app
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    description: This is a documentation of foodie's app
tags:
    - name: Users
      description: Auth operations, user info and list operation with followers.
servers:
    - url: http://localhost:3000
# paths:
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
